name: booking_system_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cinetpay: ^1.0.6
  cloud_firestore: ^4.4.5
  country_picker: 2.0.19
  firebase_auth: null
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_pagination: ^3.0.0
  firebase_remote_config: ^3.0.15
  firebase_storage: ^11.0.16
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.0.4
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^14.1.1
  flutter_launcher_icons: ^0.13.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_stripe: ^9.0.0+1
  flutter_svg: 1.1.6
  flutter_vector_icons: ^2.0.0
  flutterwave_standard: ^1.0.7
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  google_sign_in: ^6.0.2
  html: ^0.15.2
  html_unescape: ^2.0.0
  http: ^0.13.5
  image_picker: ^0.8.7
  intl: null
  lottie: ^2.3.0
  mobx: ^2.1.4
  nb_utils: ^5.0.6
  onesignal_flutter: 3.4.1
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  razorpay_flutter: ^1.3.4
  the_apple_sign_in: ^1.1.1
  translator: ^0.1.7
  url_launcher: ^6.1.10
  uuid: ^3.0.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_app_logo.png"
  remove_alpha_ios: true

dev_dependencies:
  build_runner: ^2.3.3
  change_app_package_name: ^0.1.3
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/
    - assets/lottie/
